name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: 'Automated Version Bump'
    uses: 'phips28/gh-action-bump-version@master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

