name: Build and release

on:
  push:
    branches:
      - main

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Setup Node.js, Build, Publish
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}
      - run: npm ci
      - run: npm test

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
