name: CI
on: pull_request
jobs:

  tests:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Load current commit
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests and check coverage
        run: npm test
